### ISSUE TITLE
Accès à partir de comptes Université de Bordeaux et Université Bordeaux Montaigne

### ISSUE THREAD

**Issue by pagiraud** [lovasoa/ophirofox#11]
Bonjour,

J’ai forké ophirofox pour ajouter les accès depuis ces deux universités. Je fais des tests dans Chromium et Firefox mais les deux échouent de la même façon : 

Premier clic sur un lien "Lire sur Europresse" : je suis redirigé vers la page d’authentification de l’université puis j’arrive sur la page de connexion d’Europresse… et rien ne se passe. L’URL qui s’affiche alors est de type : https://nouveau-europresse-com.docelec.u-bordeaux.fr/Login/?ReturnUrl=%2fSearch%2fReading%3fophirofox_source%3dhttps%253A%252F%252Fwww.lemonde.fr%252Feconomie%252Farticle%252F2022%252F10%252F05%252Faux-ex-fonderies-du-poitou-la-vie-d-apres_6144521_3234.html%26ophirofox_keywords%3dAux%2bex-fonderies%2bdu%2bPoitou%252C%2bla%2bvie%2bd%25E2%2580%2599apr%25C3%25A8s&ophirofox_source=https%3a%2f%2fwww.lemonde.fr%2feconomie%2farticle%2f2022%2f10%2f05%2faux-ex-fonderies-du-poitou-la-vie-d-apres_6144521_3234.html&ophirofox_keywords=Aux+ex-fonderies+du+Poitou%2c+la+vie+d%e2%80%99apr%c3%a8s

Clics suivants : idem sauf que je ne passe pas par la case authentification.

Pourtant, je ne pense pas avoir fait d’erreur.

 ```
{
    name: "Université Bordeaux Montaigne",
    domains: ["u-bordeaux-montaigne.fr"],
    LOGIN_URL: "http://ezproxy.u-bordeaux-montaigne.fr/login",
    AUTH_URL:
      "http://ezproxy.u-bordeaux-montaigne.fr/login?url=https://nouveau.europresse.com/access/ip/default.aspx?un=UNIVMONTAIGNET_1",
  },
  {
    name: "Université de Bordeaux",
    domains: ["u-bordeaux.fr"],
    LOGIN_URL: "https://docelec.u-bordeaux.fr/login",
    AUTH_URL:
      "https://docelec.u-bordeaux.fr/login?url=https://nouveau.europresse.com/access/ip/default.aspx?un=UNIVBORDEAUXT_1",
  },
```
Comme vous pouvez le voir, la configuration pour l’université de Bordeaux est très similaire à celle de l’INSA Lyon, et je ne vois pas pourquoi cela marcherait dans un cas et pas dans l’autre.

J’aimerais bien pouvoir profiter de cette extension qui a l’air super.

**Comment by mcuilleret** [comment]
Bonjour,
Concernant l'université de Bordeaux, cela fonctionne de mon coté en ajoutant au config.js: 
  {
    name: "Université de Bordeaux",
    domains: ["u-bordeaux.fr"],
    LOGIN_URL: "https://docelec.u-bordeaux.fr/login",
    // URL à charger pour pouvoir se logger sans mot de passe
    AUTH_URL:
      "http://docelec.u-bordeaux.fr/login?url=https://nouveau.europresse.com/access/ip/default.aspx?un=UNIVBORDEAUXT_1",
  },
  
  et en modifiant ulterieurement le manifest.json en y ajoutant:
          "https://nouveau-europresse-com.docelec.u-bordeaux.fr/Search/Reading*"
        "https://nouveau-europresse-com.docelec.u-bordeaux.fr/Login*"
        "https://nouveau-europresse-com.docelec.u-bordeaux.fr/Search/ResultMobile*"
 
 Avec cela ça marche normalement.
