### ISSUE TITLE
Suggestion : ajout de l'Est républicain en presse régionale

### ISSUE THREAD

**Issue by Deeane** [lovasoa/ophirofox#120]

**Comment by lovasoa** [comment]
Les contributions sont les bienvenues !

**Comment by Deeane** [comment]
Quel type de contributions ?

**Comment by lovasoa** [comment]
Si vous voulez ajouter l'est républicain, il faut contribuer un petit fichier à ophirofox, du même type que [celui du figaro](https://github.com/lovasoa/ophirofox/blob/master/ophirofox/content_scripts/lefigaro.js) par exemple. Cela demande de maîtriser un peu de HTML et de Javascript. Ensuite il faut ouvrir une proposition de contribution ici, sur github.

**Comment by Deeane** [comment]
Je ne maîtrise rien de tout cela...

**Comment by lnoss** [comment]
@lovasoa, est-ce que tu peux clore suite à #150 ?
