### ISSUE TITLE
Suggestion / question : connexion automatique avec enregistrement préalable des identifiants institutionnels ?

### ISSUE THREAD

**Issue by Deeane** [lovasoa/ophirofox#121]
Bonjour, je ne sais si la chose est déjà possible, en tout cas je n'ai pas trouvé comment, mais ce serait pratique de ne pas avoir à se reconnecter à chaque fois à europresse. Si l'extension pouvait être configurée de manière à avoir déjà nos identifiants enregistrés, ça économiserait une étape à chaque fois. Merci d'avance pour vos éclaircissements sur ce point !

**Comment by lovasoa** [comment]
C'est théoriquement possible, mais l'extension devrait demander plus de permissions, et je ne sais pas si les reviewers de google verraient d'un très bon oeil une extension qui collecte les identifiants des utilisateurs...
