### ISSUE TITLE
Titres à ajouter

### ISSUE THREAD

**Issue by Robilliart** [lovasoa/ophirofox#123]
Serait-il possible d'ajouter les titres suivants:
Les Echos
L'Equipe
L'Opinion
LSA
l'Histoire

Merci

**Comment by lovasoa** [comment]
Oui, tout est possible! Les contributions au code sont les bienvenues!

**Comment by Write** [comment]
Les Echos, L'Opinion et LSA sont maintenant disponibles.

En revanche pour l'Equipe et L'Histoire, je n'ai jamais aucun résultat retourné par Europresse : est-il possible que l'accès soit différent selon les universités ?

Si la réponse est non, je pense que l'issue peut être alors close.

**Comment by lovasoa** [comment]
Très bien, je ferme. On peut ouvrir des issues séparées pour chaque titre
