### ISSUE TITLE
L'Orient le Jour ?

### ISSUE THREAD

**Issue by regicid** [lovasoa/ophirofox#161]
Bonjour et merci pour cette merveilleuse extension !

Je voulais proposer d'ajouter L'Orient le Jour, qui est dans Europresse et est une source essentielle sur l'actualité libanaise et au moyen orient en général. J'espère ne pas être le seul !

Il me semble par contre que les articles apparaissent avec un certain délai. Je trouve celui-ci, daté d'hier : https://www.lorientlejour.com/article/1353527/derriere-le-quasi-silence-de-samir-geagea.html
Mais pas celui-là : https://www.lorientlejour.com/article/1353563/guerre-israel-gaza-quel-role-veut-jouer-la-chine-.html

Bonne journée,

Benoît de Courson

**Comment by lovasoa** [comment]
Bonjour et merci de votre message ! Les contributions sont les bienvenues, si quelqu'un veut l'implémenter.
