### ISSUE TITLE
[Le Monde Diplomatique] Problème de parseur ?

### ISSUE THREAD

**Issue by cyrileroy** [lovasoa/ophirofox#162]
Bonjour,

Merci pour cette extension.

Le renvoi vers les articles du Monde Diplomatique intègre des mentions du type "TIT_HEAD= La fin du désenchantement pour les ex guérilleros **small class fine nbsp small**", qui ont pour conséquence une absence de résultat sur Europresse.

Un problème de parseur lors de la récupération de la balise h1 dans le code HTML ?

Bonne journée,
Cyril

**Comment by lovasoa** [comment]
Merci de l'avoir remonté. J'ai publié une nouvelle version
