### ISSUE TITLE
Disparition du bouton "Lire sur Europresse" sur les articles du journal La Croix

### ISSUE THREAD

**Issue by pagiraud** [lovasoa/ophirofox#17]
Suite à quelques changements très mineurs de mise en page sur le site de La Croix, le bouton est en partie caché voire complètement inaccessible.

**Comment by tea4or2wo** [comment]
Bonjour, je me permets de commenter pour réouverture ou nouv issue, je ne sais pas si c'est le même problème ? mais le bouton semble avoir de nouveau disparu sur la Croix.

**Comment by Write** [comment]
> Bonjour, je me permets de commenter pour réouverture ou nouv issue, je ne sais pas si c'est le même problème ? mais le bouton semble avoir de nouveau disparu sur la Croix.

Bonjour, pas de problème de mon côté sur Firefox, il faudrait rouvrir une issue en ajoutant plus de détails,

Merci.
