### ISSUE TITLE
Université Bretagne Sud : ajout dans les partenaires supportés

### ISSUE THREAD

**Issue by SCDUBS56** [lovasoa/ophirofox#170]
Bonjour,
J'ai modifié le fichier demandé et, selon moi, le code est à jour pour notre établissement. Malheureusement, la modification ne remonte pas au niveau de l'extension, bien que j'ai effectué une "pull request". J'imagine donc qu'il y a une erreur quelque part, mais où ?
Pourriez-vous faire lé nécessaire pour m'aider, ou bien m'indiquer comment procéder ?
Je vous en remercie sincèrement par avance.
Bien cordialement,
Hélène Daüy

**Comment by lovasoa** [comment]
Je vois une pull request acceptée pour la bretagne occidentale, mais rien pour bretagne sud: https://github.com/lovasoa/ophirofox/pulls?q=bretagne

**Comment by lovasoa** [comment]
Je viens d'ouvrir une pull request pour vous avec vos changements: https://github.com/lovasoa/ophirofox/pull/171

**Comment by lovasoa** [comment]
Je vois que vous vous étiez fait des pull requests à vous-mêmes : https://github.com/SCDUBS56/ophirofox/pulls?q=is%3Apr+is%3Aclosed

C'est vers le dépôt "officiel" qu'il faut faire une pull request pour que votre travail soit intégré :slightly_smiling_face:
