### ISSUE TITLE
Impossible de sélectionner quoi que ce soit dans les autorisations sur Kiwi

### ISSUE THREAD

**Issue by ElanorGamegie** [lovasoa/ophirofox#176]
Bonjour,

Quand j'installe l'extension sur Kiwi Browser, il est impossible de cocher bnf sur les autorisations, le curseur ne marche pas.

J'ai vu que quelqu'un avait eu le même problème, mais installer une version antérieure à la 2.3 n'a pas marché chez moi, l'extension a des erreurs et disparaît toute seule peu de temps après... SOS!

**Comment by lovasoa** [comment]
Bonjour et bienvenue sur ophirofox !

  Essayons de regrouper les discussions à ce sujet en un seul endroit: https://github.com/lovasoa/ophirofox/issues/139

Cordialement,
Ophir
