### ISSUE TITLE
BM Lyon non sélectionnable

### ISSUE THREAD

**Issue by th-four** [lovasoa/ophirofox#181]
Bonjour,

Dans la liste des partenaires, dans les préférences de l'extension sous Firefox, la plupart des partenaires semblent sélectionnables, sauf la Bibliothèque Municipale de Lyon:

https://github.com/lovasoa/ophirofox/assets/77244229/0707542d-5538-4c38-ba98-ce5dc8bf55e4

Je n'ai pas l'impression que l'entrée de la BM Lyon soit particulièrement différente dans le `manifest.json` (en dehors du long paramètre `url` qui ressemble beaucoup à un token de session), à première vue je ne vois pas ce qui peut causer ce bug...

Merci d'avance!

**Comment by lovasoa** [comment]
C'est corrigé :)
