### ISSUE TITLE
[🔑 Auth] Ajouter la possibiliter de se connecter via Toutatice

### ISSUE THREAD

**Issue by ebanDev** [lovasoa/ophirofox#183]
Bonjour,

Toutatice est l'ENT développé par l'académie de Rennes (35), il n'utilise pas de proxy pour se connecter à europresse l'URL est directement `https://nouveau.europresse.com/`. Le process d'auth de ce que j'ai pu comprendre à partir de ce que j'ai extrait avec burpsuite est le suivant

1. Ouverture de toutatice
2. Click sur le lien de login
3. Redirection vers `educonnect` (plateforme d'auth centralisée de l'éducation nationale)
4. Une fois la connexion effectuée, redirection vers le bureau toutatice avec les bons cookies
5. De ce bureau, click vers Europesse
6. Création d'un cookie d'authentification à partir d'identifiants SAML à partir de l'URL `https://nouveau.europresse.com/Login/Gar?ticket=ST-1028-XXXXXXXXXXXXXXXX-idp-auth.gar.education.fr`

@lovasoa si vous souhaitez implémenter ce process d'auth, je pourrais vous fournir le XML que m'a donné Burpsuite avec tout le processus d'auth complet.

Merci,
Eban

**Comment by lovasoa** [comment]
Vous pouvez ouvrir une pr, il suffit d'ajouter le lien de login dans le manifest.json de l'extension

**Comment by ebanDev** [comment]
D'accord, merci ! :)
