### ISSUE TITLE
Redirige vers la page de recherche mais pas vers l'article (accès BNF)

### ISSUE THREAD

**Issue by Gullumluvl** [lovasoa/ophirofox#187]
Bonjour,

j'ai un accès BNF, mais j'atterris seulement sur la page de recherche d'Europress : https://nouveau-europresse-com.bnf.idm.oclc.org/Search/Reading

Par exemple en partant de : 
https://www.lemonde.fr/cinema/article/2024/01/17/les-films-a-l-affiche-pauvres-creatures-animal-krisha-et-le-maitre-de-la-foret-la-tete-froide_6211164_3476.html,
avec le bouton Ophirofox qui contient le lien : 
https://bnf.idm.oclc.org/login?url=https://nouveau.europresse.com/access/ip/default.aspx?un=D000067U_1

Versions :
Firefox 121.0.1
Ophirofox 2.4.26005.50437

J'ai testé en fenêtre privée en désactivant toutes les extensions.

Est-ce normal ? Et Europresse n'a pas de système de requête d'article directement via l'URL ?

Merci !

**Comment by Write** [comment]
Bonjour Gullumluvl,

Ta version d'Ophirofox ne semble par contre pas être à jour, chez moi j'ai la 2.4.26025.29760

---

Réponse original : 

> Par exemple en partant de : https://www.lemonde.fr/cinema/article/2024/01/17/les-films-a-l-affiche-pauvres-creatures-animal-krisha-et-le-maitre-de-la-foret-la-tete-froide_6211164_3476.html, avec le bouton Ophirofox qui contient le lien : https://bnf.idm.oclc.org/login?url=https://nouveau.europresse.com/access/ip/default.aspx?un=D000067U_1

Bizarre ça marche bien pour moi sous Firefox, l'extension inscrit dans le localStorage dans une variable spécifique à Ophirofox, le titre de ton article en cours au moment du clique sur "Lire sur Europresse", et cela doit du coup chercher cette variable au moment de l'affichage de la page Europresse pour l'inscrire dans la barre de recherche Europresse.
Il faudrait voir la console (où la console de l'extension ?) si elle contient une erreur js spécifique à l'extension. 


>  Et Europresse n'a pas de système de requête d'article directement via l'URL ?

Il semblerait que non, il n'y a pas de documentation a ce sujet de disponible.

**Comment by Gullumluvl** [comment]
Merci pour le retour. Ça y est j'ai mis Ophirofox à jour, désolé. Même problème cependant.

Voici la console de firefox en image, je ne maîtrise pas ce domaine et il n'y a rien qui me parle ^^'. Par contre, où trouver la console de l'extension ?

![screenshot_2024-01-21_europresse-bnf](https://github.com/lovasoa/ophirofox/assets/7593801/2e82e9c6-928e-44a2-ae04-e4882d90d182)

**Comment by Gullumluvl** [comment]
En tout cas, pas de problème sur Chromium, même avec mes dix mille extensions.

**Comment by Gullumluvl** [comment]
Bonjour,

je me suis rendu compte que je n'avais pas donné toutes les autorisations nécessaires. En retournant sur les paramètres de l'extension il y avait un gros bandeau rouge indiquant "donner l'autorisation pour europresse" 😅

Voilà voilà, désolé pour le temps passé.

Merci pour cette super extension !
