### ISSUE TITLE
[Site web] Bug affichage partenaires d’Europresse / presse nationale

### ISSUE THREAD

**Issue by Altonss** [lovasoa/ophirofox#217]
Edit: Souci d'affiche sur le site web https://ophirofox.ophir.dev/  (voir captures d'écran plus bas):
- sur chromium les partenaires d'Europresse sont affichés à la place de la liste de la presse nationale;
- sur firefox aucune liste des partenaires d'Europresse ne s'affiche.

**Comment by lovasoa** [comment]
Je ne suis pas sûr de comprendre... Peut-être que vous pourriez expliquer le problème avec des captures d'écran ?

Sur firefox, on peut choisir son établissement (*partenaire europresse*) dans les préférences de l'extension, dans `about:addons`.

![image](https://github.com/lovasoa/ophirofox/assets/552629/c0631ce3-7200-4186-aaa3-c3fc74f6fe77)

**Comment by lovasoa** [comment]
Est-ce que ce ne serait pas un problème avec une extension que vous avez installée sur votre Firefox ? Chez moi, la liste s'affiche.

**Comment by lovasoa** [comment]
corrigé avec https://github.com/lovasoa/ophirofox/commit/5740890ba87d2879cfd72db12f52460c65096b54
