### ISSUE TITLE
The Washington Post, The Economist

### ISSUE THREAD

**Issue by fmoncomble** [lovasoa/ophirofox#219]
Bonsoir,

Les deux publications citées en objet sont référencées par Europresse, mais uniquement sous forme de liens qui renvoient au site d'origine. L'intérêt de les inclure dans les sites pris en charge est donc limité.

![Screenshot 2024-04-09 at 22 59 51](https://github.com/lovasoa/ophirofox/assets/59739627/2df0036c-2baa-4aee-90bc-c165ff9664da)

![Screenshot 2024-04-09 at 23 00 16](https://github.com/lovasoa/ophirofox/assets/59739627/722ebd58-dfa2-454a-ac0e-537bfe369d63)

C'est peut-être aussi le cas d'autres publications étrangères, je n'ai pas testé tous les ajouts récents.

**Comment by RmbxCh** [comment]
Bonjour,

Effectivement, ça n'a peut-être pas beaucoup de sens de garder les liens vers Europresse dans ce cas-là.
Pour les autres titres de presse étrangère que j'ai ajoutés (Financial Times, de morgen, de standaard,  gazet van antwerpen, het laastse nieuws, het nieuwsblad, knack etc), ce n'est a priori pas le cas; les articles, quand ils sont disponibles, sont lisibles en intégralité sur Europresse. 

Par contre, c'est sans doute tout bête à faire, mais je ne sais pas comment on supprime des fichiers par PR ^^
