### ISSUE TITLE
MAJ de l'extension sur Chrome

### ISSUE THREAD

**Issue by RmbxCh** [lovasoa/ophirofox#224]
Bonjour,

La dernière mise à jour de l'extension sur Chrome date du 2 février, est-ce que vous savez si la dernière version sera bientôt dispo sur ce navigateur ?

Merci d'avance,
Bonne journée!

**Comment by lovasoa** [comment]
Je l'ai postée, c'est en attente de google

![image](https://github.com/lovasoa/ophirofox/assets/552629/61ffce73-2354-4823-9db3-00141b7b2a8b)
