### ISSUE TITLE
Ajout de l'ENS de Lyon ? 

### ISSUE THREAD

**Issue by tristanlorriaux** [lovasoa/ophirofox#23]
Salut ! 
L'extension et le travail fait sont super, aussi je pensais qu'on pourrait rajouter l'ENS de Lyon via notre BU, Diderot.
Je fournis ici les paramètres pour Europresse : 

``` javascript
 {
    name: "ENS de Lyon",
    domains: ["ens-lyon.fr"],
    LOGIN_URL: "https://acces.bibliotheque-diderot.fr/login",
    // URL à charger pour pouvoir se logger sans mot de passe
    AUTH_URL:
      "https://acces.bibliotheque-diderot.fr/login?url=https://nouveau.europresse.com/access/ip/default.aspx?un=ENSLYONT_1",
  }
```

Merci d'avance pour la réponse 🚀

**Comment by lovasoa** [comment]
Bonjour, bien sûr! Il vous faut modifier le code pour ajouter les paramètres, bien le tester en local sur votre ordinateur, et quand vous pouvez garantir que tout fonctionne bien, ouvrir une Pull Request ici sur github avec les changements, et un petit mot dans le README

**Comment by lovasoa** [comment]
L'extension fonctionne maintenant avec l'ENS Lyon :)
