### ISSUE TITLE
Liberation

### ISSUE THREAD

**Issue by dominique-r** [lovasoa/ophirofox#233]
Bonjour, 

Je ne voie plus le lien  lire dans Europresse pour libération ?
![ophirofox_liberation](https://github.com/lovasoa/ophirofox/assets/4264006/ce725bb9-bf63-4bcf-94d8-d07adcc22ca3)

NB pour Le monde par exemple, aucun pb (et très bon fonctionnement)

Cordialement

**Comment by dominique-r** [comment]
FireFox 115.14.0esr (64 bits) sur du Windows 10 Entreprise (version 22H2)
Je viens de retester ce matin, idem : bon fonctionnement sur le monde.fr, pas de bouton europresse pour liberation.fr
... ?

**Comment by Write** [comment]
Avez-vous bien la dernière version d'Ophirofox ? 
Pouvez-vous voir s'il y a des erreurs dans la console ?

**Comment by dominique-r** [comment]
Je viens d'accepter la màj que demandait ophirofox (et que je n'avait pas vu :-\)
Et en effet maintenant, cela fonctionne comme attentu sur le site de Libération.
Désolé : -\\ et Merci !

**Comment by Write** [comment]
pas de soucis :-)
