### ISSUE TITLE
Bug concernant l'autofill des titres des articles

### ISSUE THREAD

**Issue by SOY75** [lovasoa/ophirofox#235]
Bonjour à tous !
J'ai un bug avec l'extension depuis longtemps donc je me résous à reporter le problème ici:

Lorsque je click sur _Lire sur Europresse_; l'autofill va fonctionner à une seule reprise sans soucis mais ensuite ça me remet systématiquement le titre de l'article précédent sur "recherche express", je dois cliquer sur "Rechercher simple pour que ça actualise l'article. Sinon je peux me déconnecter d'europresse, puis de m'y reconnecter, ça refonctionne une fois.

 Le problème survient systématiquement sur Firefox (Windows 10) mais aussi parfois sur Mac (safari avec l'userscript et Orion)
J'ai accordé toutes les permissions dans les réglages.
J'ai essayé de clearles cookies, le cache.
Tous les journaux sont concernés.
Je me connecte via Europresse sans intermédiaire ( https://nouveau.europresse.com/Search/Result )

Je peux fournir des logs si vous me dites où ça se trouve exactement, ou vous prétez mes accès europresse pour que vous puissiez regarder directement (envoyez moi votre e-mail)

Merci beaucoup par avance, excellente journée.

**Comment by SOY75** [comment]
Voici les logs de la console: 
![1](https://github.com/user-attachments/assets/867742b3-5982-43ef-80b7-a19d1b71e2d1)
![2](https://github.com/user-attachments/assets/671b1c92-747e-4bda-8c7b-f3677f05653d)
![3](https://github.com/user-attachments/assets/6b88564a-9526-480c-ba8a-2094195a8d68)

**Comment by Write** [comment]
Problème que j'avais en effet remarqué ici https://github.com/Write/ophirofox-userscript/issues/1

Quand tu m'avais prêté tes logs, j'avais pu voir, de mémoire, c'était parce que la page vers laquelle le site "natif" vers laquelle redirige Europresse n'est pas la même que pour tous les autres domaines : de ce fait la destruction dans la mémoire du navigateur ne se fait jamais, où quelque chose de cet ordre-là.

**Comment by Write** [comment]
Écoute je vais voir pour fix le problème, tu peux me renvoyer ton compte à github@socialspill.com ?

Merci

**Comment by SOY75** [comment]
C'est super gentil de regarder. Je viens de te renvoyer mon compte.

**Comment by Write** [comment]
Cela devrait être ok :)

**Comment by SOY75** [comment]
ET en 15 minutes, merveilleux !
Merci ! Je te tiens au courant.
