### ISSUE TITLE
Langue du site web

### ISSUE THREAD

**Issue by Altonss** [lovasoa/ophirofox#246]
La langue du site web https://ophirofox.ophir.dev/ est indiquée `en-US`, mais devrait en fait être `fr`: cela pose par exemple un souci dans Firefox qui propose de traduire le site en français alors qu'il n'y a pas besoin.

**Comment by lovasoa** [comment]
Ah oui :grimacing: Il faudrait quelqu'un pour lire la doc de github pages pour voir comment changer ça: https://docs.github.com/en/pages

**Comment by Write** [comment]
C'est réglé 😁
