### ISSUE TITLE
Bug avec les titres contenant des guillemets anglais (" ") 

### ISSUE THREAD

**Issue by EEXNTISO** [lovasoa/ophirofox#25]
https://www.lemonde.fr/idees/article/2023/03/08/la-fameuse-amitie-sans-limites-decretee-par-poutine-et-xi-a-trouve-ses-limites-et-elles-ne-jouent-pas-pour-la-russie_6164570_3232.html
« La fameuse “amitié sans limites” décrétée par Poutine et Xi a trouvé ses limites, et elles ne jouent pas pour la Russie »

Une fois rentré dans Europresse le titre devient : 
TEXT= La fameuse amitié ! limites décrétée @ Poutine Xi a trouvé ses limites elles ne jouent pas pour la Russie
Aucun résultat.

**Comment by bgrenet** [comment]
It is probably enough to add the line 
```
.replace(/[^a-zA-Z0-9]/g, '')
```
between lines 7 & 8 of `europress_search.js`.

**Comment by lovasoa** [comment]
Est-ce que vous voulez faire une pull request ?

**Comment by bgrenet** [comment]
Je vais d'abord tester... mais oui ensuite je ferai ça !

**Comment by lnoss** [comment]
De même, ce ticket peut être fermé.
