### ISSUE TITLE
Est-ce qu'il y a une raison pour laquelle l'extension n'est pas dans le store Firefox ?

### ISSUE THREAD

**Issue by Erwyn** [lovasoa/ophirofox#263]
Bonjour !

Déjà merci pour l'extension qui rend un très bon service, fini les recherches à la main.

Globalement la question tient dans le titre, est-ce qu'il y a une raison pour laquelle l'extension n'est pas dans le store Firefox ?

**Comment by Write** [comment]
Hello, problème soulevé ici : https://github.com/lovasoa/ophirofox/issues/201

**Comment by Erwyn** [comment]
Merci pour le pointeur. Et désolé, j'ai visiblement très mal fait mes recherches.
