### ISSUE TITLE
Muséum national d'histoire naturelle

### ISSUE THREAD

**Issue by vbat-vbat** [lovasoa/ophirofox#33]
Bonjour,
Merci pour cette précieuse extension (enfin!).
Est-il possible d'ajouter l'accès Europress du Muséum national d'histoire naturelle?
Grand merci!
V.

**Comment by lovasoa** [comment]
Désolé, je n'avais pas vu que vous aviez aussi ouvert une issue. J'ai répondu ici: https://github.com/lovasoa/ophirofox/issues/34
