### ISSUE TITLE
Authentification

### ISSUE THREAD

**Issue by fmoncomble** [lovasoa/ophirofox#43]
Bonjour,

J'ai modifié le code pour ajouter le support de l'Université d'Artois.
Voici les URL que j'ai ajoutées aux fichiers config.js et manifest.json :

- http://ezproxy.univ-artois.fr/login?url=https://nouveau.europresse.com/access/ip/default.aspx?un=littoralT_1
- https://nouveau-europresse-com.ezproxy.univ-artois.fr/Search/Reading*
- https://nouveau-europresse-com.ezproxy.univ-artois.fr/Search/Login*
- https://nouveau-europresse-com.ezproxy.univ-artois.fr/Search/ResultMobile*

La redirection se fait correctement, la page d'authentification de l'université s'affiche, mais ensuite j'arrive sur une page d'authentification propre à Europresse et je ne peux aller plus loin…
<img width="444" alt="Screenshot 2023-08-14 at 12 19 12" src="https://github.com/lovasoa/ophirofox/assets/59739627/03b8e7d0-a784-496e-aadd-cbc8e9ac9479">

J'ai pourtant l'impression d'avoir suivi le modèle…

Merci pour toute aide !

FM

**Comment by lovasoa** [comment]
Bonjour ! Est-ce que vous pouvez ouvrir une pull request (en mode *draft* pour le moment) pour partager votre code ?

Normalement c'est l script europresse_login qui gère l'authentification ici.

https://github.com/lovasoa/ophirofox/blob/master/ophirofox/manifest.json#L150-L170

**Comment by fmoncomble** [comment]
Merci pour votre réponse !

Oui, j'ai fait l'erreur d'insérer "Search" dans l'URL Login. J'ai rectifié, maintenant Firefox me dit que "File ~/ophirofox.xpi does not contain a valid manifest".
J'ouvre un pull request pour que vous puissiez examiner le code…
