### ISSUE TITLE
Accès à partir d'un compte de la BNF

### ISSUE THREAD

**Issue by fypc** [lovasoa/ophirofox#5]
Comment serait-il possible d'adapter le plugin pour intégrer le site de la [BNF](https://www.bnf.fr) comme partenaire d'Europresse ? L'adresse de connexion à Europresse à partir de la BNF est `https://bnf.idm.oclc.org/login?url=http://nouveau.europresse.com/access/ip/default.aspx?un=bnf`.

**Comment by lovasoa** [comment]
Bonjour,
  Il vous faut modifier `config.js` pour ajouter une entrée pour la BNF.
  Voilà les modifications associées au dernier site qui a été ajoute, comme référence: https://github.com/lovasoa/ophirofox/pull/4/files

  Une fois que vous avez fait les modifications, vous pouvez les tester directement dans votre navigateur avec le système de chargement d'extensions temporaires.

Dans firefox par exemple, charger l'URL [`about:debugging#/runtime/this-firefox`](about:debugging#/runtime/this-firefox)

![image](https://user-images.githubusercontent.com/552629/153600049-f199dd7a-977e-4690-a3c0-d137b808625d.png)


Une fois que vous vous êtes assuré que vos modifications fonctionnent bien, vous pouvez [ouvrir une pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) ici avec vos changements

**Comment by fypc** [comment]
Merci pour l'information ! Je viens d'effectuer les modifications nécessaires:

<img width="1127" alt="Screen Shot 2022-02-11 at 15 14 18" src="https://user-images.githubusercontent.com/61040830/153607883-3947faf8-9565-4aef-8a08-392f7f816eeb.png">

<img width="1163" alt="Screen Shot 2022-02-11 at 15 14 37" src="https://user-images.githubusercontent.com/61040830/153607970-0fcaf783-87c1-44ac-8a44-c870288f2b82.png">

<img width="1160" alt="Screen Shot 2022-02-11 at 15 14 53" src="https://user-images.githubusercontent.com/61040830/153607990-b7a98b45-b931-4d8a-897f-d92955750ca5.png">

Sur Chrome, après m'être identifié sur l'espace personnel de la BnF, je n'obtiens que ceci :

<img width="1207" alt="Screen Shot 2022-02-11 at 15 13 33" src="https://user-images.githubusercontent.com/61040830/153608443-aafd52f1-a7b2-41fb-9d2e-23e8156b8ae5.png">

**Comment by lovasoa** [comment]
est-ce que vous êtes sûrs de votre LOGIN_URL ? Elle ne ressemble pas à celles des autres partenaires europresse...

**Comment by fypc** [comment]
Effectivement, mais il semblerait que ce soit pourtant le bon LOGIN_URL. Cette page [easyBnF](https://easybnf.fr/) utilise d'ailleurs le même URL `https://bnf.idm.oclc.org/login?url=http://nouveau.europresse.com/access/ip/default.aspx?un=bnf` pour accéder directement à Europresse.

**Comment by almottier** [comment]
Pourquoi la BnF est marquée comme supportée sur le README alors que ce n'est pas le cas ?

**Comment by pagiraud** [comment]
J’ai rencontré un problème similaire avec la configuration pour l’UBM. Le centre de documentation indiquait cette adresse pour Europresse : http://ezproxy.u-bordeaux-montaigne.fr/login?url=https://nouveau.europresse.com/access/ip/default.aspx?un=UNIVMONTAIGNET_1

Et http://ezproxy.u-bordeaux-montaigne.fr/login renvoie bien vers le système de SSO. Simplement, une fois dans le script, cela ne fonctionnait pas : 

> <img alt="Screen Shot 2022-02-11 at 15 13 33" width="1207" src="https://user-images.githubusercontent.com/61040830/153608443-aafd52f1-a7b2-41fb-9d2e-23e8156b8ae5.png">

Voilà exactement ce que j’obtenais. J’ai essayé en passant en HTTPS mais visiblement aucun certificat SSL n’a été souscrit pour le sous-domaine. En cherchant dans mon historique de navigation, j’ai trouvé une autre URL. Et en l’utilisant, Ophirofox fonctionne correctement…

```
  {
    name: "Université Bordeaux Montaigne",
    domains: ["u-bordeaux-montaigne.fr"],
    LOGIN_URL: "https://www.ezproxy.u-bordeaux-montaigne.fr/login",
    AUTH_URL:
      "https://www.ezproxy.u-bordeaux-montaigne.fr/login?url=https://nouveau.europresse.com/access/ip/default.aspx?un=UNIVMONTAIGNET_1",
  },
```
Cela n’explique en rien la cause du dysfonctionnement, mais c’est peut-être une piste pour vous.

**Comment by alexture** [comment]
Tout fonctionne parfaitement pour moi via la BNF, ça a peut-être été réparé depuis ?

**Comment by lovasoa** [comment]
Oui, la bnf fonctionne désormais
