### ISSUE TITLE
Le Devoir

### ISSUE THREAD

**Issue by fmoncomble** [lovasoa/ophirofox#50]
Bonjour,

Je cherche à ajouter la prise en charge du journal Le Devoir (Québec). Le site donne droit à trois articles gratuits, puis à partir du quatrième affiche une "surcouche" invitant à s'abonner ou à se connecter :
![Screenshot 2023-08-15 at 20 21 57](https://github.com/lovasoa/ophirofox/assets/59739627/8116f6e0-0d79-4227-9efa-8be0cd98b804)
Mes tentatives d'adapter le code dans un fichier ledevoir.js se soldent toutes par un échec :

````
async function makeEuropresseUrl() {
    const keywords = extractKeywords();
    return await makeOphirofoxReadingLink(keywords);
}

function extractKeywords() {
    return document.querySelector("h1").textContent;
}

async function createLink() {
    const a = document.createElement("a");
    a.href = await makeEuropresseUrl(new URL(window.location));
    a.textContent = "Lire sur Europresse";
    a.className = "ophirofox-europresse";
    return a;
}


function findPremiumBanner() {
    const title = document.querySelector(".pw-vignette");
    if (!title) return null;
    const elems = title.parentElement.querySelectorAll("h2");
    return [...elems].find(d => d.textContent.includes("Vous avez lu tous vos articles gratuits"))
}

async function onLoad() {
    const premiumBanner = findPremiumBanner();
    if (!premiumBanner) return;
    premiumBanner.after(await createLink());
}

onLoad().catch(console.error);
````

Des idées ?

FM

**Comment by lovasoa** [comment]
Attendez, avant de l'ajouter: est-ce que ce site existe sur europresse ? Quand je cherche l'article de votre screenshot, par exemple, je ne trouve rien.

**Comment by lovasoa** [comment]
De plus, en regardant le site, il me semble qu'il suffit d'ouvrir une fenêtre de navigation privée pour accéder aux articles. Ce n'est pas comme les autres sites qui ont du contenu qui n'est pas publiquement accessible.

**Comment by fmoncomble** [comment]
Il est bien répertorié sur Europresse, mais il se peut qu'il y ait un délai pour les articles les plus récents. 

La limite de 3 articles vaut en fenêtre normale ou privée, mais je viens de me rendre compte que chaque nouvelle ouverture de fenêtre privée remet le compteur à zéro… Merci d'avoir attiré mon attention là-dessus ! Je m'échinais pour rien…

Bonne soirée
