### ISSUE TITLE
Ajout de L'Humanité

### ISSUE THREAD

**Issue by marioxygen** [lovasoa/ophirofox#6]
Bonjour, ce plugin est magnifique ! Merci infiniment. Est-il possible d'ajouter L'Humanité qui est comme Le Monde, Le Figaro et Libé accessible sur Europresse ?

**Comment by lovasoa** [comment]
Oui ! Il faut ajouter un "content script" sur le modèle des autres sites:

 - https://github.com/lovasoa/ophirofox/tree/master/ophirofox/content_scripts
 - https://github.com/lovasoa/ophirofox/blob/master/ophirofox/manifest.json#L48-L58

Une fois que vous l'avez ajouté, vous pouvez le tester localement, et si cela fonctionne bien, faire une "pull request" ici pour l'intégrer.

**Comment by marioxygen** [comment]
Malheureusement, je n'ai pas beaucoup de compétences en la matière et, même avec l'aide du modèle, ne sais pas comment faire pratiquement.

**Comment by TrakJohnson** [comment]
@marioxygen au cas où cela vous soit encore utile, L'Humanité a été ajouté il y a quelques jours (#21) et est je crois disponible dans la dernière mise à jour.

**Comment by lovasoa** [comment]
C'est en cours de validation sur le play store, google n'est pas très rapide, et a déjà refusé une version parce que la description de l'extension ne leur plaisait pas
