### ISSUE TITLE
Les articles plus vieux que 7 jours n'apparaissent pas par défaut

### ISSUE THREAD

**Issue by TrakJohnson** [lovasoa/ophirofox#63]
En utilisant l'extension avec un article plus vieux que 7 jours, europresse affiche par défaut "Aucun résultat" (Par exemple: https://www.monde-diplomatique.fr/2023/08/MOROZOV/65981). 

C'est très simple à résoudre manuellement, en changeant le paramètre de la recherche de "Depuis 7 jours" à "Dans toutes les archives" par exemple. Par contre, je pense que c'est déroutant pour un utilisateur non averti. 

Est-ce qu'utiliser le paramètre "Dans toutes les archives" par défaut semble raisonnable ? Avec le titre entier comme keywords, je ne pense pas que le filtre temporel soit très utile.

**Comment by lovasoa** [comment]
Merci, c'est corrigé
